### PR TITLE
Bugfixes and new features

### PR DESCRIPTION
**Pull request by rpezzi**
- Option to select MFT track initialization from vertexing or outgoing parameters and covariances
- New candidate cut functions: Cut3Sigma and CutNSigma (cuts if any parameters is off by more than 3/N standard deviations
- Fix cut calculation on matchCut3SigmaXYAngles
- Fix bug on saveGlobalMuonTracks (Branch was being recreated at each event, resulting in huge filesize)
- Disk-by-disk MCS effect evaluation during track fitting

### CODE REVIEW

**Comment by rpezzi** [comment]
@bovulpes , the changes on `GlobalMuonChecks.C` are only the vector of MCLabels for the MFT. Others are formatting applied by my text editor. Sorry for that. I am missing something on clang configuration to apply it systematically in this project. We should use the same as O2.

**Review by bovulpes — APPROVED** [review]
I did not look in all the content. At some point, this stuff should also be hidden in a compiled library.

**Comment by bovulpes** [comment]
Maybe the cluster topology dictionary should not be part of this repository, actually no binary file at all. I have noticed that between two pythia simulations for the generation of this dictionary the result slightly differs, even with a quite large statistics.

**Comment by rpezzi** [comment]
Thanks, Bogdan. Indeed the dictionary is not ideal. We can replace it by two executions of the MFT reconstruction workflow, with dictionary creation in between.

**Pull request merged**
